version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: filiperochs-actual-budget_app_1
      APP_PORT: "5006"
      PROXY_AUTH_ADD: "false"

  app:
    image: actualbudget/actual-server:25.12.0
    volumes:
      - ${APP_DATA_DIR}/data:/data
    restart: unless-stopped
